from __future__ import annotations

from pathlib import Path

import sclite


ROOT = Path(__file__).resolve().parents[1]

EXPECTED_PUBLIC_EXPORTS = (
    '__version__',
    'VerificationLimits',
    'REVIEW_BUNDLE_MANIFEST_FILE',
    'REVIEW_BUNDLE_MARKDOWN_FILE',
    'REVIEW_BUNDLE_RECEIPT_FILE',
    'REVIEW_BUNDLE_REQUIRED_FILES',
    'ReviewBundleError',
    'export_review_bundle_markdown',
    'materialize_review_bundle',
    'review_bundle',
    'review_bundle_summary',
    'validate_review_bundle_shape',
    'CHAIN_CANONICALIZATION_VERSION',
    'CHAIN_HASH_ALGORITHM',
    'ChainVerificationError',
    'artifact_descriptor',
    'build_artifact_chain_manifest',
    'verify_artifact_chain_manifest',
    'verify_lifecycle_manifest',
    'OBSERVATION_SCHEMA_REF',
    'FINDING_SCHEMA_REF',
    'REACTION_PLAN_SCHEMA_REF',
    'ESCALATION_PROPOSAL_SCHEMA_REF',
    'build_observation_envelope',
    'build_finding',
    'build_reaction_plan',
    'build_reaction_chain_manifest',
    'reaction_idempotency_key',
    'validate_escalation_proposal',
    'verify_reaction_chain_manifest',
    'TRIGGER_DECISION_SCHEMA',
    'TRIGGER_DECISION_SCHEMA_REF',
    'build_trigger_decision',
    'trigger_decision_descriptor',
    'trigger_decision_digest',
    'validate_trigger_decision',
    'WATCHDOG_DECISION_SCHEMA',
    'WATCHDOG_DECISION_SCHEMA_REF',
    'build_watchdog_decision',
    'watchdog_decision_descriptor',
    'watchdog_decision_digest',
    'validate_watchdog_decision',
    'AUTOMATION_CHAIN_ARTIFACT_TYPE',
    'AUTOMATION_CHAIN_NON_CLAIMS',
    'AUTOMATION_CHAIN_SCHEMA',
    'AUTOMATION_CHAIN_SCHEMA_REF',
    'automation_chain_digest',
    'automation_owner_migration_contract',
    'automation_edge',
    'automation_node',
    'build_automation_chain',
    'validate_automation_chain',
    'verify_automation_chain',
    'KERNEL_GUARD_PROFILE',
    'KERNEL_GUARD_MINIMUM_KEY_BYTES',
    'KernelGuardKeyPolicy',
    'KernelGuardError',
    'build_kernel_guard_manifest',
    'manifest_metadata_digest',
    'verify_kernel_guard_manifest',
    'SECURE_BUNDLE_POSTURE',
    'SECURE_BUNDLE_PROFILE',
    'SecureBundleError',
    'resolve_guard_path',
    'resolve_manifest_path',
    'verify_secure_bundle',
    'verify_secure_bundle_result',
    'VERIFICATION_RESULT_SCHEMA_REF',
    'VERIFICATION_RESULT_SCHEMA_REF_V1_1',
    'VerificationResult',
    'build_guarded_strict_verification_result',
    'serialize_verification_result',
    'SCLiteError',
    'SCLiteValidationError',
    'SCLiteSchemaValidationError',
    'DISCLOSURE_STATUS_ORDER',
    'DisclosureStatus',
    'DisclosureStatusError',
    'build_disclosure_status',
    'legacy_public_safe',
    'relative_public_path',
    'validate_disclosure_transition',
    'REVIEW_RECORD_SCHEMA',
    'REVIEW_RECORD_SCHEMA_REF',
    'ReviewRecordError',
    'build_review_record_from_manifest',
    'review_record_markdown',
    'LIFECYCLE_SCOPE_FIDELITY_SCHEMA_REF',
    'LIFECYCLE_SCOPE_FIDELITY_SCHEMA_VERSION',
    'SCOPE_FIDELITY_ARTIFACT_TYPE',
    'SCOPE_FIDELITY_SCHEMA_REF',
    'SCOPE_FIDELITY_SCHEMA_VERSION',
    'build_lifecycle_scope_fidelity_report',
    'build_scope_fidelity_report',
    'build_scope_fidelity_report_from_approved_spec',
    'summarize_scope_fidelity',
    'validate_lifecycle_scope_fidelity_report',
    'validate_scope_fidelity_report',
    'SCOPED_TICKET_SCHEMA_REF',
    'TICKET_PROFILES',
    'TicketSemanticError',
    'TicketUseVerificationError',
    'explain_ticket',
    'normalized_args_digest',
    'ticket_summary',
    'validate_ticket_schema',
    'validate_ticket_semantics',
    'verify_ticket_use',
)


def test_top_level_public_api_exports_are_frozen() -> None:
    assert sclite.__all__ == EXPECTED_PUBLIC_EXPORTS, (
        'top-level public API changed; update EXPECTED_PUBLIC_EXPORTS and docs/PUBLIC_API.md intentionally'
    )
    for name in EXPECTED_PUBLIC_EXPORTS:
        assert hasattr(sclite, name), f'{name} is listed in sclite.__all__ but is not exported'


def test_public_api_doc_lists_all_frozen_exports() -> None:
    text = (ROOT / 'docs' / 'PUBLIC_API.md').read_text(encoding='utf-8')
    for name in EXPECTED_PUBLIC_EXPORTS:
        assert f'`{name}`' in text, f'{name} missing from docs/PUBLIC_API.md; document public API additions intentionally'
