from __future__ import annotations

from ._version import SCLITE_VERSION

__version__ = SCLITE_VERSION

from ._json import VerificationLimits

from .bundles import (
    REVIEW_BUNDLE_MANIFEST_FILE,
    REVIEW_BUNDLE_MARKDOWN_FILE,
    REVIEW_BUNDLE_RECEIPT_FILE,
    REVIEW_BUNDLE_REQUIRED_FILES,
    ReviewBundleError,
    export_review_bundle_markdown,
    materialize_review_bundle,
    review_bundle,
    review_bundle_summary,
    validate_review_bundle_shape,
)
from .integrity import (
    CHAIN_CANONICALIZATION_VERSION,
    CHAIN_HASH_ALGORITHM,
    ChainVerificationError,
    artifact_descriptor,
    build_artifact_chain_manifest,
    verify_artifact_chain_manifest,
    verify_lifecycle_manifest,
)
from .kernel_guard import (
    KERNEL_GUARD_MINIMUM_KEY_BYTES,
    KERNEL_GUARD_PROFILE,
    KernelGuardKeyPolicy,
    KernelGuardError,
    build_kernel_guard_manifest,
    manifest_metadata_digest,
    verify_kernel_guard_manifest,
)
from .secure import (
    SECURE_BUNDLE_POSTURE,
    SECURE_BUNDLE_PROFILE,
    SecureBundleError,
    resolve_guard_path,
    resolve_manifest_path,
    verify_secure_bundle,
    verify_secure_bundle_result,
)
from .verification_result import (
    VERIFICATION_RESULT_SCHEMA_REF_V1_1,
    VERIFICATION_RESULT_SCHEMA_REF,
    VerificationResult,
    serialize_verification_result,
)
from .errors import SCLiteError, SCLiteSchemaValidationError, SCLiteValidationError
from .disclosure import (
    DISCLOSURE_STATUS_ORDER,
    DisclosureStatus,
    DisclosureStatusError,
    build_disclosure_status,
    relative_public_path,
    validate_disclosure_transition,
)
from .review import (
    REVIEW_RECORD_SCHEMA,
    REVIEW_RECORD_SCHEMA_REF,
    ReviewRecordError,
    build_review_record_from_manifest,
    review_record_markdown,
)
from .scope_fidelity import (
    LIFECYCLE_SCOPE_FIDELITY_SCHEMA_REF,
    LIFECYCLE_SCOPE_FIDELITY_SCHEMA_VERSION,
    SCOPE_FIDELITY_ARTIFACT_TYPE,
    SCOPE_FIDELITY_SCHEMA_REF,
    SCOPE_FIDELITY_SCHEMA_VERSION,
    build_lifecycle_scope_fidelity_report,
    build_scope_fidelity_report,
    build_scope_fidelity_report_from_approved_spec,
    summarize_scope_fidelity,
    validate_lifecycle_scope_fidelity_report,
    validate_scope_fidelity_report,
)
from .tickets import (
    SCOPED_TICKET_SCHEMA_REF,
    TICKET_PROFILES,
    TicketSemanticError,
    TicketUseVerificationError,
    explain_ticket,
    normalized_args_digest,
    ticket_summary,
    validate_ticket_schema,
    validate_ticket_semantics,
    verify_ticket_use,
)
from .frontdoor import (
    ArtifactDescriptor,
    VerificationPolicy,
    VerifiedArtifact,
    VerifiedBundle,
    verify_artifact,
    verify_bundle,
)
from .schema_resolver import (
    ImmutableSchemaResolver,
    SchemaInventoryEntry,
    SchemaResolutionError,
    SchemaResolver,
)
__all__ = (
    '__version__',
    'ArtifactDescriptor',
    'VerificationPolicy',
    'VerifiedArtifact',
    'VerifiedBundle',
    'verify_artifact',
    'verify_bundle',
    'ImmutableSchemaResolver',
    'SchemaInventoryEntry',
    'SchemaResolutionError',
    'SchemaResolver',
    'VerificationLimits',
    'REVIEW_BUNDLE_MANIFEST_FILE',
    'REVIEW_BUNDLE_MARKDOWN_FILE',
    'REVIEW_BUNDLE_RECEIPT_FILE',
    'REVIEW_BUNDLE_REQUIRED_FILES',
    'ReviewBundleError',
    'export_review_bundle_markdown',
    'materialize_review_bundle',
    'review_bundle',
    'review_bundle_summary',
    'validate_review_bundle_shape',
    'CHAIN_CANONICALIZATION_VERSION',
    'CHAIN_HASH_ALGORITHM',
    'ChainVerificationError',
    'artifact_descriptor',
    'build_artifact_chain_manifest',
    'verify_artifact_chain_manifest',
    'verify_lifecycle_manifest',
    'KERNEL_GUARD_PROFILE',
    'KERNEL_GUARD_MINIMUM_KEY_BYTES',
    'KernelGuardKeyPolicy',
    'KernelGuardError',
    'build_kernel_guard_manifest',
    'manifest_metadata_digest',
    'verify_kernel_guard_manifest',
    'SECURE_BUNDLE_POSTURE',
    'SECURE_BUNDLE_PROFILE',
    'SecureBundleError',
    'resolve_guard_path',
    'resolve_manifest_path',
    'verify_secure_bundle',
    'verify_secure_bundle_result',
    'VERIFICATION_RESULT_SCHEMA_REF',
    'VERIFICATION_RESULT_SCHEMA_REF_V1_1',
    'VerificationResult',
    'serialize_verification_result',
    'SCLiteError',
    'SCLiteValidationError',
    'SCLiteSchemaValidationError',
    'DISCLOSURE_STATUS_ORDER',
    'DisclosureStatus',
    'DisclosureStatusError',
    'build_disclosure_status',
    'relative_public_path',
    'validate_disclosure_transition',
    'REVIEW_RECORD_SCHEMA',
    'REVIEW_RECORD_SCHEMA_REF',
    'ReviewRecordError',
    'build_review_record_from_manifest',
    'review_record_markdown',
    'LIFECYCLE_SCOPE_FIDELITY_SCHEMA_REF',
    'LIFECYCLE_SCOPE_FIDELITY_SCHEMA_VERSION',
    'SCOPE_FIDELITY_ARTIFACT_TYPE',
    'SCOPE_FIDELITY_SCHEMA_REF',
    'SCOPE_FIDELITY_SCHEMA_VERSION',
    'build_lifecycle_scope_fidelity_report',
    'build_scope_fidelity_report',
    'build_scope_fidelity_report_from_approved_spec',
    'summarize_scope_fidelity',
    'validate_lifecycle_scope_fidelity_report',
    'validate_scope_fidelity_report',
    'SCOPED_TICKET_SCHEMA_REF',
    'TICKET_PROFILES',
    'TicketSemanticError',
    'TicketUseVerificationError',
    'explain_ticket',
    'normalized_args_digest',
    'ticket_summary',
    'validate_ticket_schema',
    'validate_ticket_semantics',
    'verify_ticket_use',
)
